Lab 12/Models/CalcModel.cs
using System.ComponentModel.DataAnnotations;

namespace Lab_12.Models
{
    public class CalcModel
    {
        [Required(ErrorMessage = "error")]
        public double Num1 { get; set; }

        [Required(ErrorMessage = "error")]
        public double Num2 { get; set; }

        [Required(ErrorMessage = "error")]
        public OperationType Operation { get; set; }
    }
}

Lab 12/Models/ErrorViewModel.cs
namespace Lab_12.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab 12/Models/OperationType.cs
using System.ComponentModel.DataAnnotations;

namespace Lab_12.Models
{
    public enum OperationType
    {
        [Display(Name = "+")]
        Add,
        [Display(Name = "-")]
        Subtract,
        [Display(Name = "*")]
        Multiply,
        [Display(Name = "/")]
        Divide
    }
}

Lab 12/Controllers/CalculatorController.cs
using Microsoft.AspNetCore.Mvc;
using Lab_12.Models;
using System.ComponentModel.DataAnnotations;
using System.Reflection;

namespace Lab_12.Controllers
{
    // CalculatorController.cs
    public class CalculatorController : Controller
    {

        /* MODEL PARSING IN SINGLE ACTION */
        [HttpGet]
        public IActionResult IndexManualParsingInSingleAction()
        {
            return View();
        }

        [HttpPost]
        public IActionResult IndexManualParsingInSingleAction(IFormCollection form)
        {

            var num1Str = form["num1"];
            var num2Str = form["num2"];
            var operationStr = form["operation"];

            if (double.TryParse(num1Str, out double num1) && 
                double.TryParse(num2Str, out double num2) && 
                Enum.TryParse(operationStr, out OperationType operation))
            {
                double result = operation switch
                {
                    OperationType.Add => num1 + num2,
                    OperationType.Subtract => num1 - num2,
                    OperationType.Multiply => num1 * num2,
                    OperationType.Divide => num2 != 0 ? num1 / num2 : double.NaN,
                    _ => 0
                };

                ViewBag.Num1 = num1;
                ViewBag.Num2 = num2;
                ViewBag.Operation = GetOperationSymbol(operation);
                ViewBag.Result = double.IsNaN(result) ? "Деление на ноль" : result.ToString();

                return View("IndexResult");
            }
            else
            {
                ViewBag.Error = "ОШИБКА: Некорректный ввод";
                return View();
            }
        }
        /* MODEL PARSING IN SINGLE ACTION */


        // для изъятия из enum соответствубщего знака
        private string GetOperationSymbol(OperationType operation)
        {
            var displayAttribute = operation.GetType()
                                            .GetMember(operation.ToString())[0]
                                            .GetCustomAttribute<DisplayAttribute>();
            return displayAttribute?.Name ?? operation.ToString();
        }


        /* MODEL PARSING IN SEPARATE ACTIONS */
        [HttpGet]
        public IActionResult IndexManualParsingInSeparateActions()
        {
            return View();
        }

        [HttpPost]
        public IActionResult IndexManualParsingInSeparateActions(IFormCollection form)
        {

            var num1 = form["num1"];
            var num2 = form["num2"];
            var operation = form["operation"];

            // Action - Validation
            if (!Validate(num1, num2, operation, out double firstNumber, out double secondNumber, out OperationType selectedOperation))
            {
                return View();
            }

            // Action - Calculate 
            double result = Calculate(firstNumber, secondNumber, selectedOperation);

            ViewBag.Num1 = firstNumber;
            ViewBag.Num2 = secondNumber;
            ViewBag.Operation = GetOperationSymbol(selectedOperation);
            ViewBag.Result = double.IsNaN(result) ? "Деление на ноль" : result.ToString();

            return View("IndexResult");
        }

        // Action - Validation
        private bool Validate(string num1, string num2, string operation, out double firstNumber, out double secondNumber, out OperationType selectedOperation)
        {
            bool isValid = true;
            firstNumber = secondNumber = 0;
            selectedOperation = OperationType.Add; // default

            if (!double.TryParse(num1, out firstNumber) || !double.TryParse(num2, out secondNumber))
            {
                ViewBag.Error = "ОШИБКА: Некорректный ввод";
                isValid = false;
            }

            if (!Enum.TryParse(operation, out selectedOperation))
            {
                ViewBag.Error = "ERROR";
                isValid = false;
            }

            return isValid;
        }

        // Action - Calculate
        private double Calculate(double num1, double num2, OperationType operation)
        {
            return operation switch
            {
                OperationType.Add => num1 + num2,
                OperationType.Subtract => num1 - num2,
                OperationType.Multiply => num1 * num2,
                OperationType.Divide => num2 != 0 ? num1 / num2 : double.NaN,
                _ => 0
            };
        }
        /* MODEL PARSING IN SEPARATE ACTIONS */


        /* MODEL BINDING (PARAMETERS) */
        [HttpGet]
        public IActionResult IndexModelBindingParameters()
        {
            return View();
        }

        [HttpPost]
        public IActionResult IndexModelBindingParameters(string num1, string num2, OperationType operation)
        {

            if (!double.TryParse(num1, out double number1) || !double.TryParse(num2, out double number2))
            {
                ViewBag.Error = "ОШИБКА: Некорректный ввод";
                return View();
            }

            double result = operation switch
            {
                OperationType.Add => number1 + number2,
                OperationType.Subtract => number1 - number2,
                OperationType.Multiply => number1 * number2,
                OperationType.Divide => number2 != 0 ? number1 / number2 : double.NaN,
                _ => 0
            };

            ViewBag.Num1 = num1;
            ViewBag.Num2 = num2;
            ViewBag.Operation = GetOperationSymbol(operation);
            ViewBag.Result = double.IsNaN(result) ? "Деление на ноль" : result.ToString();

            return View("IndexResult");
        }
        /* MODEL BINDING (PARAMETERS) */




        /* MODEL BINDING (SEPARATE MODEL) */
        [HttpGet]
        public IActionResult IndexModelBindingSeparateModel()
        {
            return View();
        }

        [HttpPost]
        public IActionResult IndexModelBindingSeparateModel(CalcModel model)
        {
            if (ModelState.IsValid)
            {
                double result = model.Operation switch
                {
                    OperationType.Add => model.Num1 + model.Num2,
                    OperationType.Subtract => model.Num1 - model.Num2,
                    OperationType.Multiply => model.Num1 * model.Num2,
                    OperationType.Divide => model.Num2 != 0 ? model.Num1 / model.Num2 : double.NaN,
                    _ => 0
                };

                ViewBag.Num1 = model.Num1;
                ViewBag.Num2 = model.Num2;
                ViewBag.Operation = GetOperationSymbol(model.Operation);
                ViewBag.Result = double.IsNaN(result) ? "Деление на ноль" : result.ToString();
                return View("IndexResult");
            }
            else
            {
                ViewBag.Error = "ОШИБКА: Некорректный ввод";
                return View();
            }
        }
        /* MODEL BINDING (SEPARATE MODEL) */
    }
}

Lab 12/Controllers/HomeController.cs
using Lab_12.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Lab_12.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab 12/Views/Calculator/IndexManualParsingInSeparateActions.cshtml
@model Lab_12.Models.OperationType
@using Lab_12.Models

@using (Html.BeginForm("IndexManualParsingInSeparateActions", "Calculator", FormMethod.Post))
{
    <h1>ManualWithSeparateHandlers</h1>
    <p>
        @Html.TextBox("num1", "", new { type = "text", @class = "form-input" })
    </p>
    <p>
        @Html.DropDownList("operation", Html.GetEnumSelectList(typeof(OperationType)))
    </p>
    <p>
        @Html.TextBox("num2", "", new { type = "text", @class = "form-input" })
    </p>
    <p>
        <input type="submit" value="Submit" class="form-submit" />
    </p>
}
<div class="line"></div>

@if (ViewBag.Error != null)
{
    <h2>@ViewBag.Error</h2>
}

<style>

    h1 {
        font-weight: 400;
    }

    h2 {
        color: red;
        font-size: 14px;
    }

    p {
        margin: 0;
    }

    .form-input {
        padding: 5px;
        font-size: 16px;
        width: 100%;
        max-width: 320px;
        border-radius: 5px;
        border: 1px solid gray;
    }

    .form-submit {
         font-size: 16px;
         cursor: pointer;
    }

      .line {
          width: 96%;
          height: 1px;
          background-color: gray;
          opacity: 0.2;
          margin-top: 30px;
      }

</style>

Lab 12/Views/Calculator/IndexManualParsingInSingleAction.cshtml
@model Lab_12.Models.OperationType
@using Lab_12.Models

@using (Html.BeginForm("IndexManualParsingInSingleAction", "Calculator", FormMethod.Post))
{
    <h1>Manual</h1>
    <p>
        @Html.TextBox("num1", "", new { type = "text", @class = "form-input" })
    </p>
    <p>
        @Html.DropDownList("operation", Html.GetEnumSelectList(typeof(OperationType)))
    </p>
    <p>
        @Html.TextBox("num2", "", new { type = "text", @class = "form-input" })
    </p>
    <p>
        <input type="submit" value="Submit" class="form-submit" />
    </p>
}
<div class="line"></div>

@if (ViewBag.Error != null)
{
    <h2>@ViewBag.Error</h2>
}

<style>

    h1 {
        font-weight: 400;
    }

    h2 {
        color: red;
        font-size: 14px;
    }

    p {
        margin: 0;
    }

    .form-input {
        padding: 5px;
        font-size: 16px;
        width: 100%;
        max-width: 320px;
        border-radius: 5px;
        border: 1px solid gray;
    }

    .form-submit {
         font-size: 16px;
         cursor: pointer;
    }

      .line {
          width: 96%;
          height: 1px;
          background-color: gray;
          opacity: 0.2;
          margin-top: 30px;
      }

</style>

Lab 12/Views/Calculator/IndexModelBindingParameters.cshtml
@model Lab_12.Models.OperationType
@using Lab_12.Models

@using (Html.BeginForm("IndexModelBindingParameters", "Calculator", FormMethod.Post))
{
    <h1>ModelBindingInParameters</h1>
    <p>
        @Html.TextBox("num1", "", new { type = "text", @class = "form-input" })
    </p>
    <p>
        @Html.DropDownList("operation", Html.GetEnumSelectList(typeof(OperationType)))
    </p>
    <p>
        @Html.TextBox("num2", "", new { type = "text", @class = "form-input" })
    </p>
    <p>
        <input type="submit" value="Submit" class="form-submit" />
    </p>
}
<div class="line"></div>

@if (ViewBag.Error != null)
{
    <h2>@ViewBag.Error</h2>
}

<style>

    h1 {
        font-weight: 400;
    }

    h2 {
        color: red;
        font-size: 14px;
    }

    p {
        margin: 0;
    }

    .form-input {
        padding: 5px;
        font-size: 16px;
        width: 100%;
        max-width: 320px;
        border-radius: 5px;
        border: 1px solid gray;
    }

    .form-submit {
        font-size: 16px;
        cursor: pointer;
    }

    .line {
        width: 96%;
        height: 1px;
        background-color: gray;
        opacity: 0.2;
        margin-top: 30px;
    }

</style>

Lab 12/Views/Calculator/IndexModelBindingSeparateModel.cshtml
@model Lab_12.Models.CalcModel
@using Lab_12.Models

@using (Html.BeginForm("IndexModelBindingSeparateModel", "Calculator", FormMethod.Post))
{
    <h1>ModelBindingInSeparateModel</h1>
    <p>
        <input asp-for="Num1" class="form-input" type="text" />
    </p>
    <p>
        <select asp-for="Operation" asp-items="Html.GetEnumSelectList<OperationType>()"></select>
    </p>
    <p>
        <input asp-for="Num2" class="form-input" type="text" />
    </p>
    <p>
        <input type="submit" value="Submit" class="form-submit" />
    </p>
}
<div class="line"></div>

@if (ViewBag.Error != null)
{
    <h2>@ViewBag.Error</h2>
}

<style>

    h1 {
        font-weight: 400;
    }

    h2 {
        color: red;
        font-size: 14px;
    }

    p {
        margin: 0;
    }

    .form-input {
        padding: 5px;
        font-size: 16px;
        width: 100%;
        max-width: 320px;
        border-radius: 5px;
        border: 1px solid gray;
    }

    .form-submit {
        font-size: 16px;
        cursor: pointer;
    }

    .line {
        width: 96%;
        height: 1px;
        background-color: gray;
        opacity: 0.2;
        margin-top: 30px;
    }

</style>

Lab 12/Views/Calculator/IndexResult.cshtml
@{
    ViewData["Title"] = "Result";
}

<h1>Result</h1>
<p>@ViewBag.Num1 @ViewBag.Operation @ViewBag.Num2 = @ViewBag.Result</p>
<div class="line"></div>

<style>

    h1 {
        font-weight: 400;
    }

    p {
        margin: 0;
        font-size: 24px;
    }

      .line {
          width: 96%;
          height: 1px;
          background-color: gray;
          opacity: 0.2;
          margin-top: 30px;
      }

</style>

Lab 12/Views/Home/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Form parameters parsing demo</title>
    <style>
        a {
            text-decoration: none;
            font-size: 22px;
        }

        h1 {
            font-weight: 400;
            margin-top: 10px;
        }

        .line {
            width: 96%;
            height: 1px;
            background-color: gray;
            opacity: 0.2;
            margin-top: 30px;
        }
    </style>
</head>
<body>
    <h1>Form parameters parsing demo</h1>
    <nav>
        <ul>
            <li><a href="/Calculator/IndexManualParsingInSingleAction">Manual parsing in single action</a></li>
            <li><a href="/Calculator/IndexManualParsingInSeparateActions">Manual parsing in separate actions</a></li>
            <li><a href="/Calculator/IndexModelBindingParameters">Model binding (parameters)</a></li>
            <li><a href="/Calculator/IndexModelBindingSeparateModel">Model binding (separate model)</a></li>
        </ul>
    </nav>
    <div class="line"></div>
</body>
</html>

Lab 12/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Home page - Lab_12</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab_12.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab_12</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer">
        <div class="container">
            &copy; 2024 - Lab_12
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>